### ISSUE TITLE
Get http:///nitro/v1/config/csvserver: http: no Host in request URL

### ISSUE THREAD

**Issue by stephan2012** [citrix/kube-ingress-citrix-netscaler#4]
Running this ingress controller just throws

```
2018-03-25 20:57:30.974913 I | listing resource of type  csvserver
2018-03-25 20:57:30.975008 I | url: http:///nitro/v1/config/csvserver
2018-03-25 20:57:30.975061 I | Get http:///nitro/v1/config/csvserver: http: no Host in request URL
```

What is wrong?

Configuration taken from NS-ingress-controller.yaml and adjusted the `NS_URL` parameter:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nsingress
  namespace: netscaler
  labels:
    name: nsingress
spec:
  replicas: 1
  selector:
    name: nsingress
  template:
    metadata:
      labels:
        name: nsingress
    spec:
      serviceAccountName: netscaler
      imagePullSecrets:
      - name: dcr
      containers:
      - name: nsingress
        image: docker.io/adhamija/k8s:v1
        args:
        - sleep
        - infinity
        env:
        - name: NS_URL
          value: "https://netscaler.company.com/"
        - name: NS_LOGIN
          valueFrom:
            secretKeyRef:
              name: ns-login-secret
              key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ns-login-secret
              key: password
        #- name: KUBERNETES_APISERVER_ADDR
        #  value: 10.11.50.10
        #- name: KUBERNETES_APISERVER_PORT
        #  value: "8080"
```

By the way, is this project still maintained?
